packages:
  - "server"
  - "renderer"
  - "packages/*"

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  electron: true
  electron-winstaller: true
  esbuild: true
  prisma: true

confirmModulesPurge: false
